"""vercel

Revision ID: c80b99f15868
Revises: 
Create Date: 2025-07-07 01:34:44.419944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c80b99f15868'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comision', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apuntes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Date(), nullable=False),
    sa.Column('comision', sa.String(), nullable=False),
    sa.Column('juzgado', sa.String(), nullable=False),
    sa.Column('representante', sa.String(), nullable=True),
    sa.Column('procedimiento', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turno_comision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.String(), nullable=False),
    sa.Column('salta_turno', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('turno_comision')
    op.drop_table('apuntes')
    op.drop_table('agenda')
    # ### end Alembic commands ###
